bookings data added
haikuacademy/B11G04-airbnb-react pull request #53
Opened 2024-03-04 05:06 UTC by PhilJG

2024-03-04 05:12 UTC, ynotrusso requested changes

2024-03-04 05:12 UTC, ynotrusso commented on src/components/Bookings.jsx
> +        startDate: new Date(2024, 8, 22),
these should just be strings

2024-03-04 05:12 UTC, ynotrusso commented on src/components/HouseCard.jsx
> +function BookingComponent({ booking, price }) {
all of this is hardcoded in the db

2024-03-04 05:38 UTC, PhilJG reviewed
What do you want changed here?

2024-03-05 03:13 UTC, PhilJG commented on src/components/Bookings.jsx
> +        startDate: new Date(2024, 8, 22),
Don't exactly understand what you want here. I think its one of two possibilities: 

1) Make object properties into strings: But when I try to put " " around these object properties to make a string the formatter takes them off when I save

2) Turn the dates into strings: But when I try new String(new Date(2024, 3, 4)) or String(new Date(2024, 3, 4)) they still come up as an object. 

Not sure which of these you are asking for so more elaboration would be appreciated

2024-03-05 06:25 UTC, ynotrusso approved these changes

2024-03-05 06:26 UTC, merged